---
title: "Data Visualization"
author: "Erica Dale"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, #shows code
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(gapminder)

# library(sf)
```

### Read in Lizard data
```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

Refresher
Plot total length vs weight
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point()
```

Create a histogram
```{r}
ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram(color = "orange",
                 fill = "purple",
                 size = 1,
                 linetype = "dotted") #inside aes adds legend
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(
    shape = 23,
    color = "cyan4",
    fill = "purple",
    size = 4,
    alpha = 0.4
  )
```

### Changing aesthetic by variable
```{r}
ggplot(data = lizards, aes(x= total_length, 
                           y = weight)) +
  geom_point(aes(color = common_name, # lisa frank -esque
                 size = total_length),
             alpha = 0.5) +
  theme_minimal()
```

### Faceting
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_wrap(~common_name, scales = "free")
```


### Reordering

#### Summarize observation counts
```{r}
lizcount <- lizards |> 
  group_by(common_name) |> 
  summarize(tot_lizards = n())
lizcount

lizcount <- lizards |> 
  count(common_name)
lizcount
```

```{r}
ggplot(lizcount, aes(y = fct_reorder(common_name, n), 
                     x = n)) +
  geom_col()
```

```{r}
ggplot(lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name,
                 shape = common_name) +
  facet_wrap(~common_name, scales = "free_y") +
  theme_dark() # +
#  labs(x = "Total Length (mm)",
#       y = "Weight (grams)",
#       title = "Jornada Basin lizard sizes",
#       subtitle = "All lizards follow standars length-weight relationship, with Western Whiptails being largest.",
#       caption = "Data: Jornada Basin LTER, CCBY")

```

